"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.restaurant": "Restaurant",
    "nav.rooms": "Chambres",
    "nav.halls": "Salles",
    "nav.events": "Événements",
    "nav.gallery": "Galerie",
    "nav.photo": "Prises de vues",
    "nav.lake": "Lac Kivu",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.reservation": "Réservation",
    
    // Hero
    "hero.tagline": "Notre différence, votre référence",
    "hero.desc": "Une oasis de sérénité au bord du lac Kivu, où le luxe rencontre l'authenticité.",
    "hero.book": "Réserver",
    "hero.explore": "Explorer",
    "hero.find": "Nous trouver",
    "hero.cta": "Réserver maintenant",
    
    // Établissement/Restaurant
    "establishment.title": "Bienvenue à Archanges",
    "establishment.subtitle": "Excellence & Saveurs",
    "restaurant.title": "Restaurant Maman Rica",
    "restaurant.subtitle": "Gastronomie & Saveurs",
    "restaurant.tagline": "Authenticité & Raffinement",
    "restaurant.quote": "Le goût du terroir de Minova sublimé par une cuisine délicate.",
    "restaurant.desc": "Notre restaurant vous accueille dans un cadre apaisant. Notre chef utilise les meilleurs produits locaux pour créer des plats qui marient tradition et modernité.",
    "restaurant.features": "Poissons frais du lac, Petit-déjeuner complet, Service attentionné, Cadre calme, Menu varié, Produits du terroir",
    "restaurant.book": "Réserver une table",
    "restaurant.rating": "★★★★★",
    "restaurant.review_title": "Une table d'exception",
    "restaurant.testimonial": "Une expérience culinaire inoubliable au cœur du Kivu",
    
    // Salles de Réception
    "halls.title": "Salles de Réception",
    "halls.subtitle": "Événements",
    "halls.desc": "Des espaces polyvalents pour vos mariages, conférences et célébrations privées.",
    "halls.malaika": "Salle Malaika",
    "halls.malaika_subtitle": "Réunions & Séminaires",
    "halls.malaika_desc": "Cadre professionnel et modulable pour séminaires, formations et comités. Capacité jusqu'à 100 personnes.",
    "halls.arche": "Salle Arche de Noé",
    "halls.arche_subtitle": "Mariages & Grands événements",
    "halls.arche_desc": "Espace majestueux sonorisé pour mariages, galas et grandes réceptions. Jusqu'à 500 invités.",
    "halls.malaika_tags": "100 places|Projecteur|Insonorisation|Pause-café",
    "halls.arche_tags": "500 places|Scène|Climatisation|Traiteur|Sonorisation",
    "halls.book": "Réserver",
    
    // Photo/Prises de vues
    "photo.title": "Prises de vues",
    "photo.subtitle": "Espace Créatif",
    "photo.desc": "Immortalisez vos moments précieux dans un cadre exceptionnel. Entre architecture élégante et vue sur le lac, l'Hôtel Archanges offre des décors uniques pour vos séances photo et vidéos.",
    "photo.light": "Lumière & Décor",
    "photo.light_desc": "Des espaces pensés pour les créateurs de contenu et les souvenirs de famille.",
    "photo.booking": "Réserver un shooting",

    // Événements
    "events.title": "Événements & Activités",
    "events.upcoming": "À venir",
    "events.past": "Albums",
    "events.evangelism": "Concert d'Évangélisation",
    "events.evangelist": "avec Évangéliste Eustache DUNIA",
    "events.kicker": "Vie de l'hôtel",
    "events.subtitle": "Retours sur nos soirées, séminaires et moments forts au bord du lac Kivu.",
    "events.past_section": "Événements passés",
    "events.past_hint": "Ouvrez la vidéo ou l'album directement sur cette page — sans quitter le site.",
    "events.open_video": "Lire la vidéo ici",
    "events.open_album": "Voir l'album ici",
    "events.badge_video": "Vidéo",
    "events.badge_album": "Album",
    "events.close": "Fermer",
    "events.prev": "Photo précédente",
    "events.next": "Photo suivante",
    "events.external_note": "La lecture se fait dans Archanges Hôtel ; le lien YouTube reste disponible si vous préférez l'ouvrir dans un autre onglet.",
    "events.open_youtube_tab": "Ouvrir sur YouTube",
    
    // Galerie
    "gallery.title": "Galerie Photos",
    "gallery.subtitle": "Découvrez nos installations",
    "gallery.close": "Fermer",
    
    // Chambres
    "rooms.title": "Chambres & Suites",
    "rooms.subtitle": "Confort & Luxe",
    "rooms.standard": "Chambre Standard",
    "rooms.standard_desc": "Confortable et accueillante",
    "rooms.deluxe": "Chambre Deluxe",
    "rooms.deluxe_desc": "Spacieuse et luxueuse",
    "rooms.vip": "Suite VIP",
    "rooms.vip_desc": "L'excellence du luxe",
    "rooms.price": "par nuit",
    "rooms.amenities": "Équipements",
    "rooms.book": "Réserver cette chambre",
    
    // Lac Kivu
    "lake.title": "Lac Kivu",
    "lake.subtitle": "Une invitation au voyage",
    "lake.desc": "Contemplez l'horizon à perte de vue. Une parenthèse hors du temps au cœur du Sud-Kivu.",
    "lake.activities": "Activités",
    "lake.book_excursion": "Réserver une excursion",
    "lake.learn_more": "En savoir plus",
    
    // Réservation
    "booking.title": "Réservation",
    "booking.subtitle": "Réservez votre séjour",
    "booking.type": "Type de réservation",
    "booking.fullname": "Nom complet",
    "booking.email": "Adresse e-mail",
    "booking.phone": "Numéro de téléphone",
    "booking.checkin": "Date d'arrivée",
    "booking.checkout": "Date de départ",
    "booking.guests": "Nombre de personnes",
    "booking.room_type": "Type de chambre",
    "booking.message": "Message",
    "booking.submit": "Envoyer la réservation",
    "booking.success": "Réservation envoyée avec succès !",
    "booking.error_email": "Adresse e-mail invalide",
    "booking.error_phone": "Numéro de téléphone invalide (min 9 chiffres)",
    "booking.error_dates": "Les dates sont invalides",
    "booking.error_checkout": "La date de départ doit être après l'arrivée",
    "booking.page_title": "Demande de réservation",
    "booking.page_subtitle": "Renseignez le formulaire : notre équipe vous répond sous réserve de disponibilité.",
    "booking.section_identity": "Identité & coordonnées",
    "booking.section_stay": "Séjour & demande",
    "booking.section_payment": "Modalités de facturation",
    "booking.lastname": "Nom",
    "booking.firstname": "Prénom",
    "booking.country_origin": "Pays d'origine",
    "booking.nationality": "Nationalité",
    "booking.id_document": "N° carte d'identité ou passeport",
    "booking.city_origin": "Ville de provenance",
    "booking.stay_purpose": "Motif du séjour / de l'événement",
    "booking.payment_mode": "Modalité de paiement",
    "booking.payment_private": "Particulier (paiement privé)",
    "booking.payment_company": "Entreprise (partenariat / convention)",
    "booking.company_name": "Raison sociale",
    "booking.company_contact": "Contact facturation (e-mail ou téléphone)",
    "booking.accept_terms": "J'accepte les conditions de traitement des données et la prise de contact par l'hôtel.",
    "booking.accept_terms_link": "Lire les informations",
    "booking.error_required": "Champ obligatoire",
    "booking.error_accept": "Vous devez accepter les conditions pour continuer",
    "booking.error_company": "Indiquez la raison sociale et un contact entreprise",
    "booking.per_night": "nuit",
    "booking.sending": "Envoi en cours…",
    "booking.success_title": "Demande envoyée",
    "booking.success_body": "Votre demande a bien été transmise. Notre équipe vous contactera après vérification de la disponibilité.",
    "booking.close": "Fermer",
    "booking.send_error": "L'envoi a échoué. Réessayez ou contactez-nous par téléphone.",
    "booking.network_error": "Erreur de connexion. Vérifiez le réseau et réessayez.",
    "booking.res_type.room": "Chambre",
    "booking.res_type.restaurant": "Restaurant",
    "booking.res_type.event": "Salle d'événement",
    "booking.res_type.photoshoot": "Séance photo",
    "booking.ph_country": "Ex. RDC, Rwanda, France…",
    "booking.ph_id": "Comme indiqué sur le document",
    "booking.ph_purpose": "Tourisme, affaires, séminaire, mariage…",
    "booking.ph_company": "Nom légal de la société",
    "booking.privacy_blurb":
      "Vos données sont utilisées uniquement pour traiter votre demande et vous contacter au sujet de cette réservation.",
    "booking.dates": "Dates",
    "booking.wizard.breadcrumb_home": "Accueil",
    "booking.wizard.hero_title": "Votre séjour commence ici",
    "booking.wizard.hero_subtitle":
      "Un parcours clair en quelques étapes, comme sur les grands sites de réservation. Réponse personnalisée sous réserve de disponibilité.",
    "booking.wizard.progress_label": "Votre parcours",
    "booking.wizard.tab_stay": "Séjour",
    "booking.wizard.tab_guest": "Voyageur",
    "booking.wizard.tab_billing": "Facturation",
    "booking.wizard.tab_review": "Vérification",
    "booking.wizard.stay_heading": "Votre projet",
    "booking.wizard.guest_heading": "Identité du voyageur principal",
    "booking.wizard.billing_heading": "Modalités & engagement",
    "booking.wizard.review_heading": "Vérifiez et envoyez",
    "booking.wizard.review_intro":
      "Contrôlez chaque information. Vous recevrez un accusé de réception par e-mail ; la confirmation définitive viendra de l'hôtel.",
    "booking.wizard.review_guest": "Coordonnées & pièce d'identité",
    "booking.wizard.night_one": "nuit",
    "booking.wizard.night_other": "nuits",
    "booking.wizard.back": "Retour",
    "booking.wizard.next": "Continuer",
    "booking.wizard.confirm_send": "Envoyer la demande",
    "booking.wizard.summary_title": "Récapitulatif",
    "booking.wizard.summary_note_title": "Important",
    "booking.wizard.summary_note":
      "Aucun paiement en ligne n'est exigé ici. Tarif et disponibilité vous seront confirmés par notre équipe.",
    "booking.trust_secure": "Transmission sécurisée",
    "booking.trust_response": "Réponse rapide",
    "booking.trust_direct": "Ligne réception",
    "booking.promo_title": "Réservez comme dans un grand établissement",
    "booking.promo_subtitle":
      "Chambres, restaurant Maman Rica, salles Malaika & Arche de Noé, séances photo : tout est réuni dans un parcours unique, professionnel et soigné.",
    "booking.promo_cta": "Ouvrir le parcours de réservation",
    "booking.promo_trust_line": "Sans engagement · Données protégées · Archanges Hôtel",
    "booking.promo_phone_label": "Une question avant de commencer ?",

    "staff.mail_badge": "Équipe",
    "staff.mail_title": "Courrier professionnel (Zoho)",
    "staff.mail_desc":
      "Ouvrez votre webmail Zoho dans un onglet sécurisé. Les demandes envoyées depuis ce site sont aussi transmises sur reservations@archangeshotel.com.",
    "staff.mail_open_zoho": "Ouvrir Zoho Mail",
    "staff.mail_write": "Écrire aux réservations",
    "staff.mail_note":
      "Un tableau de bord réservations intégré au site (liste, statuts, disponibilité) est prévu à l'étape suivante avec base de données.",
    "staff.notify_title": "Activité & courrier",
    "staff.notify_body":
      "Après chaque nouvelle demande sur le site, une alerte apparaît ici. Ouvrez Zoho Mail pour consulter les messages professionnels.",
    
    // Paiement
    "payment.title": "Moyens de Paiement",
    "payment.subtitle": "Paiements sécurisés",
    "payment.mpesa": "M-Pesa",
    "payment.airtel": "Airtel Money",
    "payment.orange": "Orange Money",
    "payment.visa": "Visa Card",
    "payment.mastercard": "MasterCard",
    "payment.available": "Disponible",
    "payment.security": "Confidentialité & Sécurité",
    "payment.security_desc": "Vos paiements sont chiffrés et sécurisés. Vos données personnelles sont protégées.",
    
    // Services
    "services.title": "Nos Services",
    "services.subtitle": "Excellence en tous points",
    "services.concierge": "Conciergerie 24/7",
    "services.concierge_desc": "Équipe disponible jour et nuit pour vos réservations et événements",
    "services.wifi": "Star Link",
    "services.wifi_desc": "Connexion WiFi ultra-rapide et gratuite",
    "services.security": "Sécurité Totale",
    "services.security_desc": "Sécurité professionnelle 24 heures sur 24",
    "services.parking": "Parking Privé",
    "services.parking_desc": "Stationnement sécurisé pour tous les véhicules",
    "services.relax": "Espace Détente",
    "services.relax_desc": "Piscine et jardins avec vue sur le lac",
    "services.fast": "Service Rapide",
    "services.fast_desc": "Check-in et check-out express",
    "services.breakfast": "Petit-Déjeuner",
    "services.breakfast_desc": "Buffet varié : local et international",
    "services.location": "Emplacement Idéal",
    "services.location_desc": "Entre ville et nature, accès direct au lac",
    
    // Footer
    "footer.brand": "Archanges Hôtel",
    "footer.tagline": "Notre différence, votre référence",
    "footer.desc": "Une oasis de luxe au bord du lac Kivu. Archanges Hôtel redéfinit l'hospitalité avec ses chambres d'exception, le Restaurant Maman Rica et ses espaces de réception prestigieux.",
    "footer.nav": "Navigation",
    "footer.contact": "Coordonnées",
    "footer.emails": "E-mails Professionnels",
    "footer.address": "Adresse",
    "footer.phone": "Téléphone",
    "footer.website": "Site Web",
    "footer.welcome": "Accueil & informations",
    "footer.reservations": "Réservations",
    "footer.events_email": "Événements",
    "footer.management": "Direction",
    "footer.rights": "Tous droits réservés.",
    "footer.dev": "Développé par",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.restaurant": "Restaurant",
    "nav.rooms": "Rooms",
    "nav.halls": "Halls",
    "nav.events": "Events",
    "nav.gallery": "Gallery",
    "nav.photo": "Photoshoots",
    "nav.lake": "Lake Kivu",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.reservation": "Reservation",
    
    // Hero
    "hero.tagline": "Our difference, your reference",
    "hero.desc": "An oasis of serenity on the shores of Lake Kivu, where luxury meets authenticity.",
    "hero.book": "Book Now",
    "hero.explore": "Explore",
    "hero.find": "Find Us",
    "hero.cta": "Book now",
    
    // Établissement/Restaurant
    "establishment.title": "Welcome to Archanges",
    "establishment.subtitle": "Excellence & Flavors",
    "restaurant.title": "Maman Rica Restaurant",
    "restaurant.subtitle": "Gastronomy & Flavors",
    "restaurant.tagline": "Authenticity & Refinement",
    "restaurant.quote": "The taste of Minova's terroir elevated by delicate cuisine.",
    "restaurant.desc": "Our restaurant welcomes you in a peaceful setting. Our chef uses the finest local products to create dishes that blend tradition and modernity.",
    "restaurant.features": "Fresh lake fish, Full breakfast, Attentive service, Calm atmosphere, Varied menu, Local products",
    "restaurant.book": "Reserve a table",
    "restaurant.rating": "★★★★★",
    "restaurant.review_title": "An exceptional table",
    "restaurant.testimonial": "An unforgettable culinary experience in the heart of Kivu",
    
    // Salles de Réception
    "halls.title": "Reception Halls",
    "halls.subtitle": "Events",
    "halls.desc": "Versatile spaces for your weddings, conferences and private celebrations.",
    "halls.malaika": "Malaika Hall",
    "halls.malaika_subtitle": "Meetings & Seminars",
    "halls.malaika_desc": "Professional, flexible space for seminars, training and committees. Up to 100 guests.",
    "halls.arche": "Noah's Ark Hall",
    "halls.arche_subtitle": "Weddings & Large Events",
    "halls.arche_desc": "Majestic, fully equipped space for weddings, galas and large receptions. Up to 500 guests.",
    "halls.malaika_tags": "100 guests|Projector|Soundproofing|Coffee breaks",
    "halls.arche_tags": "500 guests|Stage|A/C|Catering|Sound system",
    "halls.book": "Book",
    
    // Photo/Prises de vues
    "photo.title": "Photoshoots",
    "photo.subtitle": "Creative Space",
    "photo.desc": "Capture your precious moments in an exceptional setting. Between elegant architecture and lake views, Hotel Archanges offers unique settings for your photo and video sessions.",
    "photo.light": "Light & Decor",
    "photo.light_desc": "Spaces designed for content creators and family memories.",
    "photo.booking": "Book a shoot",

    // Events
    "events.title": "Events & Activities",
    "events.upcoming": "Upcoming",
    "events.past": "Galleries",
    "events.evangelism": "Evangelism Concert",
    "events.evangelist": "with Evangelist Eustache DUNIA",
    "events.kicker": "Hotel life",
    "events.subtitle": "Highlights from our evenings, seminars and lakeside moments.",
    "events.past_section": "Past events",
    "events.past_hint": "Open the video or album here on this site—no need to leave the page.",
    "events.open_video": "Watch here",
    "events.open_album": "View album here",
    "events.badge_video": "Video",
    "events.badge_album": "Album",
    "events.close": "Close",
    "events.prev": "Previous photo",
    "events.next": "Next photo",
    "events.external_note": "Playback is embedded on Archanges Hotel; you can still open the original YouTube page if you prefer.",
    "events.open_youtube_tab": "Open on YouTube",
    
    // Gallery
    "gallery.title": "Photo Gallery",
    "gallery.subtitle": "Discover our facilities",
    "gallery.close": "Close",
    
    // Rooms
    "rooms.title": "Rooms & Suites",
    "rooms.subtitle": "Comfort & Luxury",
    "rooms.standard": "Standard Room",
    "rooms.standard_desc": "Comfortable and welcoming",
    "rooms.deluxe": "Deluxe Room",
    "rooms.deluxe_desc": "Spacious and luxurious",
    "rooms.vip": "VIP Suite",
    "rooms.vip_desc": "The height of luxury",
    "rooms.price": "per night",
    "rooms.amenities": "Amenities",
    "rooms.book": "Book This Room",
    
    // Lake Kivu
    "lake.title": "Lake Kivu",
    "lake.subtitle": "An invitation to travel",
    "lake.desc": "Contemplate the endless horizon. A break from time in the heart of South Kivu.",
    "lake.activities": "Activities",
    "lake.book_excursion": "Book an Excursion",
    "lake.learn_more": "Learn More",
    
    // Booking
    "booking.title": "Reservation",
    "booking.subtitle": "Book your stay",
    "booking.type": "Reservation Type",
    "booking.fullname": "Full Name",
    "booking.email": "Email Address",
    "booking.phone": "Phone Number",
    "booking.checkin": "Check-in Date",
    "booking.checkout": "Check-out Date",
    "booking.guests": "Number of Guests",
    "booking.room_type": "Room Type",
    "booking.message": "Message",
    "booking.submit": "Submit Booking",
    "booking.success": "Booking submitted successfully!",
    "booking.error_email": "Invalid email address",
    "booking.error_phone": "Invalid phone number (min 9 digits)",
    "booking.error_dates": "Invalid dates",
    "booking.error_checkout": "Check-out date must be after check-in",
    "booking.page_title": "Reservation request",
    "booking.page_subtitle": "Complete the form; our team will reply subject to availability.",
    "booking.section_identity": "Identity & contact",
    "booking.section_stay": "Stay & request",
    "booking.section_payment": "Billing arrangement",
    "booking.lastname": "Last name",
    "booking.firstname": "First name",
    "booking.country_origin": "Country of origin",
    "booking.nationality": "Nationality",
    "booking.id_document": "National ID or passport number",
    "booking.city_origin": "City of origin / departure",
    "booking.stay_purpose": "Purpose of stay or event",
    "booking.payment_mode": "Payment arrangement",
    "booking.payment_private": "Individual (private payment)",
    "booking.payment_company": "Company (partnership / corporate account)",
    "booking.company_name": "Company legal name",
    "booking.company_contact": "Billing contact (email or phone)",
    "booking.accept_terms": "I accept the data processing terms and being contacted by the hotel.",
    "booking.accept_terms_link": "Information",
    "booking.error_required": "This field is required",
    "booking.error_accept": "You must accept the terms to continue",
    "booking.error_company": "Please provide company name and a billing contact",
    "booking.per_night": "night",
    "booking.sending": "Sending…",
    "booking.success_title": "Request sent",
    "booking.success_body": "Your request has been received. Our team will contact you after checking availability.",
    "booking.close": "Close",
    "booking.send_error": "Sending failed. Try again or call us.",
    "booking.network_error": "Connection error. Check your network and try again.",
    "booking.res_type.room": "Room",
    "booking.res_type.restaurant": "Restaurant",
    "booking.res_type.event": "Event hall",
    "booking.res_type.photoshoot": "Photoshoot",
    "booking.res_type.excursion": "Lake Kivu Excursion",
    "booking.ph_country": "e.g. DRC, Rwanda, France…",
    "booking.ph_id": "As shown on the document",
    "booking.ph_purpose": "Leisure, business, seminar, wedding…",
    "booking.ph_company": "Legal company name",
    "booking.privacy_blurb":
      "Your data is used only to process this request and contact you about this reservation.",
    "booking.dates": "Dates",
    "booking.wizard.breadcrumb_home": "Home",
    "booking.wizard.hero_title": "Your stay starts here",
    "booking.wizard.hero_subtitle":
      "A clear, guided flow in a few steps—similar to leading booking sites. Personal reply subject to availability.",
    "booking.wizard.progress_label": "Your progress",
    "booking.wizard.tab_stay": "Stay",
    "booking.wizard.tab_guest": "Guest",
    "booking.wizard.tab_billing": "Billing",
    "booking.wizard.tab_review": "Review",
    "booking.wizard.stay_heading": "Your plans",
    "booking.wizard.guest_heading": "Lead guest details",
    "booking.wizard.billing_heading": "Billing & consent",
    "booking.wizard.review_heading": "Review & send",
    "booking.wizard.review_intro":
      "Check every detail. You will receive an acknowledgement by email; final confirmation comes from the hotel.",
    "booking.wizard.review_guest": "Contact & ID",
    "booking.wizard.night_one": "night",
    "booking.wizard.night_other": "nights",
    "booking.wizard.back": "Back",
    "booking.wizard.next": "Continue",
    "booking.wizard.confirm_send": "Submit request",
    "booking.wizard.summary_title": "Summary",
    "booking.wizard.summary_note_title": "Please note",
    "booking.wizard.summary_note":
      "No online payment is required at this stage. Rates and availability will be confirmed by our team.",
    "booking.trust_secure": "Secure submission",
    "booking.trust_response": "Quick response",
    "booking.trust_direct": "Front desk line",
    "booking.promo_title": "Book with five-star polish",
    "booking.promo_subtitle":
      "Rooms, Maman Rica restaurant, Malaika & Noah's Ark halls, photoshoots—one refined, professional flow.",
    "booking.promo_cta": "Start reservation",
    "booking.promo_trust_line": "No obligation · Protected data · Archanges Hotel",
    "booking.promo_phone_label": "Prefer to talk first?",

    "staff.mail_badge": "Staff",
    "staff.mail_title": "Professional mail (Zoho)",
    "staff.mail_desc":
      "Open your Zoho webmail in a secure browser tab. Requests from this site are also sent to reservations@archangeshotel.com.",
    "staff.mail_open_zoho": "Open Zoho Mail",
    "staff.mail_write": "Email reservations",
    "staff.mail_note":
      "An integrated reservations dashboard (list, statuses, availability) is planned in the next phase with a database.",
    "staff.notify_title": "Activity & mail",
    "staff.notify_body":
      "After each new request on the site, an alert appears here. Open Zoho Mail for your professional inbox.",
    
    // Payment
    "payment.title": "Payment Methods",
    "payment.subtitle": "Secure Payments",
    "payment.mpesa": "M-Pesa",
    "payment.airtel": "Airtel Money",
    "payment.orange": "Orange Money",
    "payment.visa": "Visa Card",
    "payment.mastercard": "MasterCard",
    "payment.available": "Available",
    "payment.security": "Privacy & Security",
    "payment.security_desc": "Your payments are encrypted and secure. Your personal data is protected.",
    
    // Services
    "services.title": "Our Services",
    "services.subtitle": "Excellence in everything",
    "services.concierge": "24/7 Concierge",
    "services.concierge_desc": "Team available day and night for your reservations and events",
    "services.wifi": "Star Link",
    "services.wifi_desc": "Ultra-fast and free WiFi throughout",
    "services.security": "Total Security",
    "services.security_desc": "Professional security 24 hours a day",
    "services.parking": "Private Parking",
    "services.parking_desc": "Secure parking for all vehicles",
    "services.relax": "Relaxation Area",
    "services.relax_desc": "Pool and gardens overlooking the lake",
    "services.fast": "Express Service",
    "services.fast_desc": "Express check-in and check-out",
    "services.breakfast": "Breakfast",
    "services.breakfast_desc": "Varied buffet: local and international",
    "services.location": "Ideal Location",
    "services.location_desc": "Between city and nature, direct lake access",
    
    // Footer
    "footer.brand": "Archanges Hotel",
    "footer.tagline": "Our difference, your reference",
    "footer.desc": "A luxury oasis on the shores of Lake Kivu. Archanges Hotel redefines hospitality with its exceptional rooms, Maman Rica Restaurant and prestigious reception spaces.",
    "footer.nav": "Navigation",
    "footer.contact": "Contact Details",
    "footer.emails": "Professional Emails",
    "footer.address": "Address",
    "footer.phone": "Phone",
    "footer.website": "Website",
    "footer.welcome": "Welcome & Info",
    "footer.reservations": "Bookings",
    "footer.events_email": "Events",
    "footer.management": "Management",
    "footer.rights": "All rights reserved.",
    "footer.dev": "Developed by",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("fr");

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
